# Generated by Django 3.0.5 on 2020-04-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matched',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
