# Generated by Django 3.0.5 on 2020-04-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_2', '0003_assigned_skills_matched_business_experience_matched_passion_matched_up_for_matched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='want_to_be_matched',
        ),
        migrations.AddField(
            model_name='user',
            name='Collaborator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='Ideamaker',
            field=models.BooleanField(default=False),
        ),
    ]
